#!/bin/sh

if test -e "$HOME"/.config/lzblue/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "3"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "5"

echo "# Enabling Flathub Beta Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
if [ "$?" != 0 ] ; then
	zenity --error \
	  --text="Adding Flathub Beta Repo Failed"
	exit 1
fi
echo "7"
echo "Enabling Gnome Nigthly Repository"
/usr/bin/flatpak remote-add --user --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
if [ "$?" != 0 ] ; then
	zenity --error \
	  --text="Adding Gnome Nightly Repo Failed"
	exit 1
fi
echo "9"

if ! test -e "$HOME"/.zshrc; then
echo "# Configuring your shell"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
kgx --title="CHANGING DEFAULT SHELL" -e "chsh -s $(which zsh) && echo 'DONE! YOU CAN CLOSE THIS WINDOW'"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
echo ZSH="${HOME}/.oh-my-zsh" >> "${HOME}"/.zshrc
cat >> "$HOME"/.zshrc << 'EOL'

#Theme
ZSH_THEME=""

#Plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

#Star Ship
eval "$(starship init zsh)"
EOL
echo "12"
fi

if ! test -e "$HOME"/.config/lzblue/firstboot.removed.uneeded; then
  echo "# Removing uneeded apps"
  /usr/bin/flatpak remove --noninteractive org.gnome.Extensions org.gnome.Cheese
  if [ "$?" != 0 ]; then
	zenity --error \
	  --text="Error removing uneeded apps"
	exit 1
  fi
fi
echo "14"

if ! test -e "$HOME"/.config/lzblue/firstboot.replace.flatpaks; then
  echo "# Replacing Fedora Flatpaks with Flathub Ones (this may take a while)"
  /usr/bin/flatpak install --user --noninteractive org.gnome.Platform//45
  /usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
  if [ "$?" != 0 ] ; then
          zenity --error \
            --text="Replacing Fedora Flatpaks Failed"
          exit 1
  fi
fi
echo "25"

echo "Removing all preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing all preinstalled flatpaks failed"
        exit 1
fi

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "30"

echo "# Installing Firefox"
/usr/bin/flatpak install --user --noninteractive flathub org.mozilla.firefox
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Firefox Failed"
        exit 1
fi
echo "35"

echo "# Installing Thunderbird"
/usr/bin/flatpak install --user --noninteractive flathub org.mozilla.Thunderbird
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Thunderbird Failed"
        exit 1
fi
echo "40"

echo "# Installing Extension Manager"
/usr/bin/flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Extension Manager Failed"
        exit 1
fi
echo "45"

echo "# Installing Ptyxis"
/usr/bin/flatpak install --user --noninteractive org.gnome.Ptyxis.Devel
if [ "$?" != 0 ] ; then
	zenity --error \
	  --text="Installing Ptyxis Failed"
	exit 1
fi
echo "50"

echo "# Installing Fractal"
/usr/bin/flatpak install --user --noninteractive flathub org.gnome.Fractal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Fractal Failed"
        exit 1
fi
echo "55"

echo "# Installing VSCode"
/usr/bin/flatpak install --user --noninteractive flathub com.visualstudio.code
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing VSCode Failed"
        exit 1
fi
echo "# Installing VSCode Podman Runtime"
/usr/bin/flatpak install --user --noninteractive flathub com.visualstudio.code.tool.podman/x86_64/23.08
if [ "$?" != 0 ] ; then
	zenity --error \
	  --text="Installing VSCode Podman Runtime Failed"
	exit 1
fi
echo "60"

echo "# Installing Pods"
/usr/bin/flatpak install --user --noninteractive flathub com.github.marhkb.Pods
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Pods Failed"
        exit 1
fi
echo "# Enable podman.socket in user"
/usr/bin/systemctl --user enable --now podman.socket
if [ "$?" != 0 ] ; then
	zenity --error \
	  --text="Error activating podman.socket"
	exit 1
fi
echo "70"

echo "# Installing Flatseal"
/usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flatseal Failed"
        exit 1
fi
echo "75"

echo "# Installing Celluloid Media Player"
/usr/bin/flatpak install --user --noninteractive flathub io.github.celluloid_player.Celluloid
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Celluloid Failed"
        exit 1
fi
echo "80"

echo "# Installing Amberol"
/usr/bin/flatpak install --user --noninteractive flathub io.bassi.Amberol
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Ambertol Failed"
        exit 1
fi
echo "95"

echo "# Installing Gnome Snapshot"
/usr/bin/flatpak install --user --noninteractive flathub org.gnome.Snapshot
if [ "$?" != 0 ] ; then
	zenity --error \
	  --text="Installing Gnome Snapshots Failed"
	exit 1
fi
echo "100"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/lzblue/
touch "$HOME"/.config/lzblue/firstboot-done
touch "$HOME"/.config/lzblue/firstboot.replace.flatpaks
touch "$HOME"/.config/lzblue/firtsboot.removed.uneeded
cp -n /etc/justfile "$HOME"/.justfile

) | 
     
   zenity --progress --title="LzBlue Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
