#!/bin/sh

if [ "$EUID" -eq 0 ]
  then echo "Don't run as root!"
  exit 1
fi

VERSION=1.0

STATE_DIR="$HOME/.local/state/lzb-manager"
TMP_DIR="$HOME/.local/"
BIN_DIR="$HOME/.local/bin"

if test ! -e $STATE_DIR; then
  mkdir -p $STATE_DIR
fi
if test ! -e $BIN_DIR; then
  mkdir -p $BIN_DIR
fi

function usage() {
  echo "LzBlue Manager Utility."
  echo
  echo "Usage:"
  echo " lzb-manager COMMAND"
  echo
  echo "Commands:"
  echo " help          Print this Help."
  echo " setup-shell   Setup user shell."
  echo " version       Print software version and exit."
  echo
}

function write_zsh_config() {
cat >> "$HOME"/.zshrc << 'EOL'

#PATH env
export PATH=$HOME/.local/bin:$PATH

#Theme
ZSH_THEME=""

#Plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

fpath+=~/.oh-my-zsh/custom/plugins/zsh-completions/src

source $ZSH/oh-my-zsh.sh

#Star Ship
eval "$(starship init zsh)"
EOL
}

function install_starship() {
  curl -Lo $TMP_DIR/starship.tar.gz "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"
  tar -xzf $TMP_DIR/starship.tar.gz -C $BIN_DIR
  rm -rf $TMP_DIR/starship.tar.gz
}

function setup_shell() {
  if test ! -e $STATE_DIR/shell.configured && test -e /bin/zsh; then
    echo "  Configuring your shell..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions
    rm -rf $HOME/.zshrc
    echo ZSH="${HOME}/.oh-my-zsh" >> "${HOME}"/.zshrc
    write_zsh_config
    install_starship
    mkdir -p $HOME/.local/share/fonts
    wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip -O $HOME/.local/share/fonts/Meslo.zip
    unzip $HOME/.local/share/fonts/Meslo.zip -d $HOME/.local/share/fonts/meslo-nerd
    rm -rf $HOME/.local/share/fonts/Meslo.zip
    fc-cache -f
    echo
    echo "Shell Configure, enjoy :)"
    echo
    touch $STATE_DIR/shell.configured
  else
    if test ! -e /bin/zsh; then
      echo "  ERROR: zsh not installed!"
      exit 1
    else
      echo "  Your shell is already configured!"
      echo "  remove the file: $STATE_DIR/shell.configured if you want to configure again"
      exit 1
    fi
  fi
}

while [ "$1" != "" ]; do
  PARAM=`echo $1 | awk -F= '{print $1}'`
  case $PARAM in
    help)
      usage
      exit
      ;;
    setup-shell)
      setup_shell
      exit
      ;;
    version)
      echo "VERSION: $VERSION"
      ;;
    *)
      echo "ERROR: unknown parameter \"$PARAM\""
      usage
      exit 1
      ;;
  esac
  shift
done


